"""stepback — time-travel debugger for AI agents.

Public surface for v0.1::

    from stepback import record, replay
    from stepback.substitutions import (
        PromptSubstitution, ToolOutputSubstitution,
        ModelSubstitution, PolicySubstitution, RouterSubstitution,
    )

`record(path)` is a context manager returning a `Recorder` whose
`llm_call(...)` and `tool_call(...)` methods append signed,
HMAC-chained frames to an append-only `.sb` file.

`replay(path)` returns a `Trace` with reversible step navigation
(`step_back`, `goto`), typed `substitute(...)`, `replay_forward(...)`,
`bisect(...)`, `branch_at(...)`, and `compare_branches(...)`.

The exhaustive public surface — every symbol that is part of the
v0.1 semver contract — is enumerated in :data:`__all__` at the bottom
of this module and snapshot-tested in ``tests/test_public_api.py``.
Every name in :data:`__all__` is required to carry a docstring; that
invariant is also enforced by the public-API test suite.
"""
from .recorder import record, arecord, get_current_recorder, Recorder, RecorderKey
from .backpressure import RecorderOptions
from .step_types import RecordedStep, Receipt, StepKind, TraceHeader
from . import autorecord
from . import testing
from .replay import replay, replay_events, Trace, Branch, BranchDiff, ReplayResult, Executor, ReplayPlan, PlannedStep, StepProvenance, ReplayProvenance, BisectTarget, BisectMultiResult, MissingExecutor, UnavailableExecutorError, StepExecutorRequirement, PartialExecutor, audit_executor_requirements
from .minimize import (
    BinaryHalvingStrategy,
    BranchGroup,
    BranchMinimizationResult,
    BruteForceStrategy,
    BudgetExhausted,
    DDMinStrategy,
    LinearShrinkStrategy,
    MinimizationResult,
    MinimizeOptions,
    MultiObjectiveDDMinStrategy,
    MultiObjectiveMinimizationResult,
    ParetoEntry,
    PredicateNotTriggered,
    ShapleyAttributionStrategy,
    StepAttributionResult,
    Strategy,
    TraceObjectives,
    attribute_steps,
    attribute_substitutions,
    ddmin_substitutions,
    extract_objectives,
    find_all_minimal,
    identify_branch_groups,
    minimize_branches,
    minimize_imported_trace,
    minimize_substitutions,
    multi_objective_minimize,
)
from . import predicates
from .predicates import (
    TypedPredicate,
    threshold,
    regex_match,
    regex_search,
    policy_check,
    callback,
)
from .attestation import (
    AttestationEntry,
    AttestationPack,
    AttestationVerificationError,
    build_attestation_pack,
    read_attestation_pack,
    verify_attestation_pack,
    write_attestation_pack,
)
from .branch_io import (
    BranchTraceMismatch,
    diff_replays,
    load_branch,
    parse_substitution_spec,
    save_branch,
    trace_chain_hash,
)
from .substitutions import (
    FieldOutputSubstitution,
    InputsPatchSubstitution,
    MessagePatchSubstitution,
    ModelSubstitution,
    OutputsPatchSubstitution,
    PolicySubstitution,
    PromptSubstitution,
    RaiseSubstitution,
    RouterSubstitution,
    SamplingSubstitution,
    Substitution,
    SubstitutionSet,
    SystemPromptSubstitution,
    ToolArgumentsSubstitution,
    ToolOutputSubstitution,
)
from .jsonpatch import (
    PatchError,
    PatchInvalidOp,
    PatchPathNotFound,
    PatchTestFailed,
    apply_patch,
)
from .trace_diff import (
    CrossTraceDiff,
    StepPair,
    diff_traces,
    render_trace_diff,
)
from .policy_audit import (
    PolicyImpactReport,
    StepImpact,
    TraceImpact,
    audit_policy_change,
    is_policy_blocked,
)
from .nondeterminism import (
    NondeterminismClass,
    forces_dirty as nondeterminism_forces_dirty,
    clock_nondeterminism,
    rng_nondeterminism,
    env_nondeterminism,
    network_nondeterminism,
    model_sampling_nondeterminism,
    combine_nondeterminism,
)
from .seeding import (  # Step 69
    SeedSupport,
    SeedWarnLevel,
    SeedPolicyViolation,
    SeedPolicyError,
    SeedPolicy,
    PROVIDER_SEED_SUPPORT,
    DEFAULT_SEED_POLICY,
    get_seed_policy,
    set_seed_policy,
)
from .divergence import (
    Divergence,
    DivergenceReport,
    DirtySetEntry,
    DirtySetSummary,
    compute_dirty_set,
    SEVERITY as DIVERGENCE_SEVERITY,
    SEVERITY_WEIGHT as DIVERGENCE_SEVERITY_WEIGHT,
    VOLATILE_KEYS as DIVERGENCE_VOLATILE_KEYS,
    compare_outputs,
    detect_divergences,
)
from .distributed_dirty import (  # Step 64
    DagRegion,
    RegionSummary,
    compute_dirty_set_distributed,
    partition_dag_regions,
)
from .distributed_bisect import (  # Step 140
    DistributedBisectItem,
    DistributedBisectOptions,
    DistributedBisectResult,
    DistributedBisectSummary,
    DistributedMultiObjectiveResult,
    DistributedMultiObjectiveSummary,
    distributed_bisect,
    distributed_multi_objective_bisect,
)
from .analytics import (  # Step 65
    ClickHouseAnalytics,
    DIRTY_SET_TABLE_DDL,
    DIRTY_SET_REPLICATED_TABLE_DDL,
    DIRTY_SET_TABLE_NAME,
    DirtySetRecord,
    record_from_summary,
    TraceStepRecord,
    TRACE_STEP_TABLE_DDL,
    TRACE_STEP_REPLICATED_TABLE_DDL,
    TRACE_STEP_TABLE_NAME,
    step_record_from_dirty_entry,
    TraceStepAnalytics,
)
from .exporters import (
    ExportError,
    ExportReport,
    TraceExportError,
    available_export_formats,
    export_cyclonedx_ai,
    export_html_view,
    export_langsmith_jsonl,
    export_native_json,
    export_openai_chat_log,
    export_openinference_spans,
    export_otel_spans,
    export_trace,
    export_trace_file,
    validate_native_json_doc,
)
from .html_view import (
    TraceViewSummary,
    render_trace_html,
    write_trace_html,
    TimeTravelSummary,
    render_time_travel_html,
    write_time_travel_html,
    FullReportSummary,
    render_full_html_report,
    write_full_html_report,
)
from .otel_bridge import (  # Step 150
    OtelBridge,
    OtelBridgeError,
    OtelBridgeExportResult,
    OtlpHttpExporter,
    DryRunCollector,
)
from .importers import (
    ImportReport,
    LossReport,
    TraceImportError,
    import_cyclonedx_ai,
    import_datadog_apm,
    import_helicone_log,
    import_langfuse_export,
    import_langsmith_jsonl,
    import_native_json,
    import_openai_chat_log,
    import_openinference_spans,
    import_otel_spans,
    import_phoenix_spans,
    import_trace,
)
from .report import (
    ReportOptions,
    render_counterfactual_report,
    render_replay_report,
    render_report_json,
    dump_report_json,
)
# Step 87: HTML minimization reports
from .minimize_report import (
    MinimizeReportOptions,
    render_html_minimize_report,
)
from .sweep import (
    DistStats,
    SweepFailure,
    SweepReport,
    SweepResult,
    render_sweep_report,
    render_sweep_report_json,
    sweep_traces,
)
from .shims import (
    AnthropicMessage,
    AsyncWrappedAnthropic,
    AsyncWrappedOpenAI,
    AzureOpenAIShimContract,
    CohereMessage,
    CohereShimContract,
    GeminiCandidate,
    GeminiResponse,
    GeminiUsageMetadata,
    MistralChatResponse,
    MistralShimContract,
    OpenAIChatCompletion,
    OpenAIResponsesOutput,
    StreamedLLMResponse,
    WrappedAnthropic,
    WrappedAzureOpenAI,
    WrappedBedrock,
    WrappedCohere,
    WrappedGemini,
    WrappedLangchainTool,
    WrappedMCPSession,
    WrappedMistral,
    WrappedOpenAI,
    # OpenAI-compatible provider types (Step 96)
    OpenAICompatShimContract,
    GroqShimContract,
    TogetherShimContract,
    FireworksShimContract,
    CerebrasShimContract,
    NvidiaNIMShimContract,
    VLLMShimContract,
    TGIShimContract,
    LlamaCppShimContract,
    OllamaShimContract,
    WrappedOpenAICompat,
    _accumulate_streaming_chunks,
    anthropic_executor,
    azure_openai_executor,
    bedrock_executor,
    canonical_azure_model_id,
    canonical_bedrock_model_id,
    canonical_cohere_model_id,
    canonical_gemini_model_id,
    canonical_mistral_model_id,
    cohere_executor,
    gemini_executor,
    langchain_tool_executor,
    mcp_tool_executor,
    mistral_executor,
    openai_executor,
    # OpenAI-compatible provider executors (Step 96)
    openai_compat_executor,
    groq_executor,
    together_executor,
    fireworks_executor,
    cerebras_executor,
    nvidia_nim_executor,
    vllm_executor,
    tgi_executor,
    llamacpp_executor,
    ollama_executor,
    wrap_anthropic,
    wrap_anthropic_async,
    wrap_azure_openai,
    wrap_bedrock,
    wrap_cohere,
    wrap_gemini,
    wrap_langchain_tool,
    wrap_langchain_tools,
    wrap_mcp_session,
    wrap_mistral,
    wrap_openai,
    wrap_openai_async,
    wrap_openai_responses,
    wrap_vertex_model,
    StepbackCallbackHandler,
    langchain_callback_handler,
    LlamaIndexCallbackHandler,
    llamaindex_callback_handler,
    DSPyCallbackHandler,
    dspy_callback_handler,
    HaystackTracer,
    haystack_tracer,
    AutoGenEventHandler,
    autogen_event_handler,
    CrewAIStepRecorder,
    crewai_step_recorder,
    SemanticKernelFilter,
    semantic_kernel_filter,
    StrandsCallbackHandler,
    strands_callback_handler,
    PydanticAIInstrument,
    pydantic_ai_instrument,
    InspectAIRecorder,
    inspect_ai_recorder,
    # OpenAI-compatible provider wrap functions (Step 96)
    wrap_groq,
    wrap_together,
    wrap_fireworks,
    wrap_cerebras,
    wrap_nvidia_nim,
    wrap_vllm,
    wrap_tgi,
    wrap_llamacpp,
    wrap_ollama,
)

from . import spec
from .spec import (
    SBTRACE_FORMAT_VERSION_TO_ENCODINGS,
    SBTRACE_FORMAT_VERSION_TO_WIRE,
    SBTRACE_WIRE_ENCODING,
    SBTRACE_WIRE_ENCODINGS,
    SBTRACE_WIRE_MAJOR,
    SBTRACE_WIRE_MINOR,
    SBTRACE_WIRE_PATCH,
    SBTRACE_WIRE_VERSION,
    SBTRACE_WIRE_VERSION_INFO,
    SBTraceConformanceError,
    SBTraceSpec,
    SBTraceVersionError,
    ConformanceIssue,
    ConformanceReport,
    current_spec,
    format_version_for_wire_version,
    is_compatible_reader,
    parse_wire_version,
    wire_version_for_format_version,
)
from ._deprecation import (
    DeprecationPolicyError,
    deprecated,
    deprecated_alias,
    format_deprecation_message,
    warn_deprecated,
)
from .sandbox import (  # Step 72: sandboxed replay modes
    SandboxMode,
    SandboxConfig,
    SandboxError,
    SandboxTimeoutError,
    SandboxResourceError,
    SandboxUnavailableError,
    SandboxViolationError,
    SandboxedExecutor,
    create_sandbox,
)
from .step_cache import (  # Step 74: sharded content-addressed step cache
    StepCacheEntry,
    StepCache,
    DiskStepCache,
    S3StepCache,
    GCSStepCache,
    AzureStepCache,
    NamespacedStepCache,
    MultiTierStepCache,
)
from .event_bus import (  # Step 75: Kafka-backed event bus + idempotency
    EventKind,
    ReplayEvent,
    EventBus,
    NullEventBus,
    InMemoryEventBus,
    KafkaEventBus,
    IdempotencyStatus,
    IdempotencyRegistry,
    InMemoryIdempotencyRegistry,
    compute_replay_idempotency_key,
    execute_with_idempotency,
)
from .worker_lease import (  # Step 76: worker leases
    LeaseStatus,
    WorkerLease,
    LeaseExpiredError,
    LeaseRegistry,
    InMemoryLeaseRegistry,
    DiskLeaseRegistry,
)
from .sweep_checkpoint import (  # Step 76: checkpointed sweep
    CheckpointEntryStatus,
    CheckpointEntry,
    SweepCheckpoint,
    DiskSweepCheckpoint,
    resume_sweep,
)
from .stability import (  # Step 82: statistical stability metrics
    FlakyClass,
    FlakyPredicateWarning,
    StabilityConfig,
    StabilityResult,
    measure_predicate_stability,
)
from .config import (  # Step 160: stepback.toml configuration loader
    ConfigError,
    TraceConfig,
    KeyConfig,
    ShimConfig,
    RedactionConfig,
    PriceListConfig,
    ViewerConfig,
    StepbackConfig,
    DEFAULT_CONFIG,
    ENV_VAR_MAP,
    SECRET_KEYS,
    find_config_file,
    load_config,
)
from .provenance import (  # Step 111: SLSA / in-toto provenance
    ProvenanceVerificationError,
    INTOTO_STATEMENT_TYPE,
    SLSA_PREDICATE_TYPE,
    DSSE_PAYLOAD_TYPE,
    BUILD_TYPE_TRACE,
    BUILD_TYPE_BENCHMARK,
    BUILD_TYPE_PACK,
    BUILDER_ID,
    MEDIA_TYPE_TRACE,
    MEDIA_TYPE_BENCHMARK,
    MEDIA_TYPE_PACK,
    trace_provenance,
    benchmark_provenance,
    pack_provenance,
    sign_provenance,
    verify_provenance_signature,
    sha256_of_file,
    sha256_of_bytes,
)

__all__ = [
    "record",
    "arecord",
    "get_current_recorder",
    "autorecord",
    "testing",
    "RecorderOptions",
    "replay",
    "replay_events",
    "Recorder",
    "RecorderKey",
    "RecordedStep",
    "Receipt",
    "StepKind",
    "TraceHeader",
    "Trace",
    "Branch",
    "BranchDiff",
    "ReplayResult",
    "Executor",
    "ReplayPlan",
    "PlannedStep",
    "StepProvenance",
    "ReplayProvenance",
    "BranchTraceMismatch",
    "diff_replays",
    "load_branch",
    "parse_substitution_spec",
    "save_branch",
    "trace_chain_hash",
    "Substitution",
    "SubstitutionSet",
    "PromptSubstitution",
    "ModelSubstitution",
    "ToolOutputSubstitution",
    "FieldOutputSubstitution",  # Step 60: partial recompute
    "PolicySubstitution",
    "RouterSubstitution",
    "SystemPromptSubstitution",
    "MessagePatchSubstitution",
    "SamplingSubstitution",
    "ToolArgumentsSubstitution",
    "InputsPatchSubstitution",
    "OutputsPatchSubstitution",
    "RaiseSubstitution",
    "apply_patch",
    "PatchError",
    "PatchInvalidOp",
    "PatchPathNotFound",
    "PatchTestFailed",
    "ReportOptions",
    "render_counterfactual_report",
    "render_replay_report",
    "render_report_json",
    "dump_report_json",
    # --- Step 87: minimize reports ------------------------------------
    "MinimizeReportOptions",
    "render_html_minimize_report",
    "CrossTraceDiff",
    "StepPair",
    "diff_traces",
    "render_trace_diff",
    "PolicyImpactReport",
    "TraceImpact",
    "StepImpact",
    "audit_policy_change",
    "is_policy_blocked",
    "OpenAIChatCompletion",
    "OpenAIResponsesOutput",
    "AsyncWrappedOpenAI",
    "AsyncWrappedAnthropic",
    "AnthropicMessage",
    # --- streaming recorder support (Step 97) -------------------------
    "StreamedLLMResponse",
    "AzureOpenAIShimContract",
    "CohereMessage",
    "CohereShimContract",
    "GeminiResponse",
    "GeminiCandidate",
    "GeminiUsageMetadata",
    "MistralChatResponse",
    "MistralShimContract",
    "WrappedOpenAI",
    "WrappedAnthropic",
    "WrappedAzureOpenAI",
    "WrappedBedrock",
    "WrappedCohere",
    "WrappedGemini",
    "WrappedLangchainTool",
    "WrappedMCPSession",
    "WrappedMistral",
    # OpenAI-compatible provider types (Step 96)
    "OpenAICompatShimContract",
    "GroqShimContract",
    "TogetherShimContract",
    "FireworksShimContract",
    "CerebrasShimContract",
    "NvidiaNIMShimContract",
    "VLLMShimContract",
    "TGIShimContract",
    "LlamaCppShimContract",
    "OllamaShimContract",
    "WrappedOpenAICompat",
    "wrap_openai",
    "wrap_openai_async",
    "wrap_openai_responses",
    "wrap_anthropic",
    "wrap_anthropic_async",
    "wrap_azure_openai",
    "wrap_bedrock",
    "wrap_cohere",
    "wrap_gemini",
    "wrap_mistral",
    "wrap_vertex_model",
    "wrap_langchain_tool",
    "wrap_langchain_tools",
    "wrap_mcp_session",
    # LangChain / LangGraph callback recorder (Step 101)
    "StepbackCallbackHandler",
    "langchain_callback_handler",
    # Framework recorders (Step 102)
    "LlamaIndexCallbackHandler",
    "llamaindex_callback_handler",
    "DSPyCallbackHandler",
    "dspy_callback_handler",
    "HaystackTracer",
    "haystack_tracer",
    "AutoGenEventHandler",
    "autogen_event_handler",
    "CrewAIStepRecorder",
    "crewai_step_recorder",
    "SemanticKernelFilter",
    "semantic_kernel_filter",
    "StrandsCallbackHandler",
    "strands_callback_handler",
    "PydanticAIInstrument",
    "pydantic_ai_instrument",
    "InspectAIRecorder",
    "inspect_ai_recorder",
    # OpenAI-compatible provider wrap functions (Step 96)
    "wrap_groq",
    "wrap_together",
    "wrap_fireworks",
    "wrap_cerebras",
    "wrap_nvidia_nim",
    "wrap_vllm",
    "wrap_tgi",
    "wrap_llamacpp",
    "wrap_ollama",
    "openai_executor",
    "anthropic_executor",
    "azure_openai_executor",
    "bedrock_executor",
    "cohere_executor",
    "gemini_executor",
    "langchain_tool_executor",
    "mcp_tool_executor",
    "mistral_executor",
    # OpenAI-compatible provider executors (Step 96)
    "openai_compat_executor",
    "groq_executor",
    "together_executor",
    "fireworks_executor",
    "cerebras_executor",
    "nvidia_nim_executor",
    "vllm_executor",
    "tgi_executor",
    "llamacpp_executor",
    "ollama_executor",
    "canonical_azure_model_id",
    "canonical_bedrock_model_id",
    "canonical_cohere_model_id",
    "canonical_gemini_model_id",
    "canonical_mistral_model_id",
    "AttestationEntry",
    "AttestationPack",
    "AttestationVerificationError",
    "build_attestation_pack",
    "read_attestation_pack",
    "verify_attestation_pack",
    "write_attestation_pack",
    "MinimizationResult",
    "PredicateNotTriggered",
    "ddmin_substitutions",
    # --- branch minimization (Step 85) --------------------------------
    "BranchGroup",
    "BranchMinimizationResult",
    "identify_branch_groups",
    "minimize_branches",
    # --- step attribution (Step 84) -----------------------------------
    "StepAttributionResult",
    "attribute_steps",
    # --- multi-objective ddmin (Step 81) ------------------------------
    "TraceObjectives",
    "ParetoEntry",
    "MultiObjectiveMinimizationResult",
    "MultiObjectiveDDMinStrategy",
    "extract_objectives",
    "multi_objective_minimize",
    # --- typed predicate DSL (Step 80) --------------------------------
    "TypedPredicate",
    "threshold",
    "regex_match",
    "regex_search",
    "policy_check",
    "callback",
    "DistStats",
    "SweepFailure",
    "SweepResult",
    "SweepReport",
    "sweep_traces",
    "render_sweep_report",
    "render_sweep_report_json",
    "Divergence",
    "DivergenceReport",
    "DirtySetEntry",
    "DirtySetSummary",
    "compute_dirty_set",
    "DIVERGENCE_SEVERITY",
    "DIVERGENCE_SEVERITY_WEIGHT",
    "DIVERGENCE_VOLATILE_KEYS",
    "compare_outputs",
    "detect_divergences",
    # --- distributed dirty-set (Step 64) -----------------------------
    "DagRegion",
    "RegionSummary",
    "compute_dirty_set_distributed",
    "partition_dag_regions",
    # --- distributed bisect (Step 140) --------------------------------
    "DistributedBisectItem",
    "DistributedBisectOptions",
    "DistributedBisectResult",
    "DistributedBisectSummary",
    "DistributedMultiObjectiveResult",
    "DistributedMultiObjectiveSummary",
    "distributed_bisect",
    "distributed_multi_objective_bisect",
    # --- ClickHouse analytics (Step 65) ------------------------------
    "ClickHouseAnalytics",
    "DIRTY_SET_TABLE_DDL",
    "DIRTY_SET_REPLICATED_TABLE_DDL",
    "DIRTY_SET_TABLE_NAME",
    "DirtySetRecord",
    "record_from_summary",
    # --- Step 139: ClickHouse step schema ----------------------------
    "TraceStepRecord",
    "TRACE_STEP_TABLE_DDL",
    "TRACE_STEP_REPLICATED_TABLE_DDL",
    "TRACE_STEP_TABLE_NAME",
    "step_record_from_dirty_entry",
    "TraceStepAnalytics",
    # --- Nondeterminism classes (Step 63) ----------------------------
    "NondeterminismClass",
    "nondeterminism_forces_dirty",
    "clock_nondeterminism",
    "rng_nondeterminism",
    "env_nondeterminism",
    "network_nondeterminism",
    "model_sampling_nondeterminism",
    "combine_nondeterminism",
    # --- Deterministic seeding policy (Step 69) ----------------------
    "SeedSupport",
    "SeedWarnLevel",
    "SeedPolicyViolation",
    "SeedPolicyError",
    "SeedPolicy",
    "PROVIDER_SEED_SUPPORT",
    "DEFAULT_SEED_POLICY",
    "get_seed_policy",
    "set_seed_policy",
    "ExportError",
    "ExportReport",
    "TraceExportError",
    "available_export_formats",
    "export_cyclonedx_ai",
    "export_langsmith_jsonl",
    "export_native_json",
    "validate_native_json_doc",
    "export_html_view",
    "export_openai_chat_log",
    "export_openinference_spans",
    "export_otel_spans",
    "export_trace",
    "export_trace_file",
    "ImportReport",
    "LossReport",
    "TraceImportError",
    "import_cyclonedx_ai",
    "import_datadog_apm",
    "import_helicone_log",
    "import_langfuse_export",
    "import_langsmith_jsonl",
    "import_native_json",
    "import_openai_chat_log",
    "import_openinference_spans",
    "import_otel_spans",
    "import_phoenix_spans",
    "import_trace",
    # --- OtelBridge (Step 150) ----------------------------------------
    "OtelBridge",
    "OtelBridgeError",
    "OtelBridgeExportResult",
    "OtlpHttpExporter",
    "DryRunCollector",
    "TraceViewSummary",
    "render_trace_html",
    "write_trace_html",
    "TimeTravelSummary",
    "render_time_travel_html",
    "write_time_travel_html",
    "FullReportSummary",
    "render_full_html_report",
    "write_full_html_report",
    # --- SB-Trace wire-format SemVer (Step 22) ----------------------
    "SBTRACE_WIRE_VERSION",
    "SBTRACE_WIRE_VERSION_INFO",
    "SBTRACE_WIRE_MAJOR",
    "SBTRACE_WIRE_MINOR",
    "SBTRACE_WIRE_PATCH",
    "SBTRACE_WIRE_ENCODING",
    "SBTRACE_WIRE_ENCODINGS",
    "SBTRACE_FORMAT_VERSION_TO_WIRE",
    "SBTRACE_FORMAT_VERSION_TO_ENCODINGS",
    "SBTraceVersionError",
    "parse_wire_version",
    "is_compatible_reader",
    "wire_version_for_format_version",
    "format_version_for_wire_version",
    # --- SBTraceSpec versioned schema validator (Step 23) -----------
    "SBTraceSpec",
    "SBTraceConformanceError",
    "ConformanceIssue",
    "ConformanceReport",
    "current_spec",
    # --- Deprecation policy helpers (Step 21) -----------------------
    "DeprecationPolicyError",
    "deprecated",
    "deprecated_alias",
    "format_deprecation_message",
    "warn_deprecated",
    # --- Sandboxed replay modes (Step 72) ----------------------------
    "SandboxMode",
    "SandboxConfig",
    "SandboxError",
    "SandboxTimeoutError",
    "SandboxResourceError",
    "SandboxUnavailableError",
    "SandboxViolationError",
    "SandboxedExecutor",
    "create_sandbox",
    # --- Sharded content-addressed step cache (Step 74) --------------
    "StepCacheEntry",
    "StepCache",
    "DiskStepCache",
    "S3StepCache",
    "GCSStepCache",
    "AzureStepCache",
    "NamespacedStepCache",
    "MultiTierStepCache",
    # --- Kafka-backed event bus + idempotency (Step 75) ---------------
    "EventKind",
    "ReplayEvent",
    "EventBus",
    "NullEventBus",
    "InMemoryEventBus",
    "KafkaEventBus",
    "IdempotencyStatus",
    "IdempotencyRegistry",
    "InMemoryIdempotencyRegistry",
    "compute_replay_idempotency_key",
    "execute_with_idempotency",
    # --- Worker leases + checkpointed sweep (Step 76) -----------------
    "LeaseStatus",
    "WorkerLease",
    "LeaseExpiredError",
    "LeaseRegistry",
    "InMemoryLeaseRegistry",
    "DiskLeaseRegistry",
    "CheckpointEntryStatus",
    "CheckpointEntry",
    "SweepCheckpoint",
    "DiskSweepCheckpoint",
    "resume_sweep",
    # --- statistical stability metrics (Step 82) ----------------------
    "FlakyClass",
    "FlakyPredicateWarning",
    "StabilityConfig",
    "StabilityResult",
    "measure_predicate_stability",
    # --- incremental multi-regression bisect (Step 83) ----------------
    "BisectTarget",
    "BisectMultiResult",
    # --- minimization for imported traces (Step 86) -------------------
    "MissingExecutor",
    "UnavailableExecutorError",
    "StepExecutorRequirement",
    "PartialExecutor",
    "audit_executor_requirements",
    "minimize_imported_trace",
    # --- SLSA / in-toto provenance (Step 111) ------------------------
    "ProvenanceVerificationError",
    "INTOTO_STATEMENT_TYPE",
    "SLSA_PREDICATE_TYPE",
    "DSSE_PAYLOAD_TYPE",
    "BUILD_TYPE_TRACE",
    "BUILD_TYPE_BENCHMARK",
    "BUILD_TYPE_PACK",
    "BUILDER_ID",
    "MEDIA_TYPE_TRACE",
    "MEDIA_TYPE_BENCHMARK",
    "MEDIA_TYPE_PACK",
    "trace_provenance",
    "benchmark_provenance",
    "pack_provenance",
    "sign_provenance",
    "verify_provenance_signature",
    "sha256_of_file",
    "sha256_of_bytes",
    # --- stepback.toml config loader (Step 160) ----------------------
    "ConfigError",
    "TraceConfig",
    "KeyConfig",
    "ShimConfig",
    "RedactionConfig",
    "PriceListConfig",
    "ViewerConfig",
    "StepbackConfig",
    "DEFAULT_CONFIG",
    "ENV_VAR_MAP",
    "SECRET_KEYS",
    "find_config_file",
    "load_config",
]

__version__ = "0.1.0"
